[profile.default]

src = "contracts"
libs = ["lib"]
remappings = [
	'@openzeppelin/contracts=lib/openzeppelin-contracts/contracts/',
	'@ensdomains/ens-contracts=lib/ens-contracts/',
	'@ensdomains/buffer=lib/buffer'
]

solc_version = "0.8.27"
optimizer = true

# forge install ensdomains/ens-contracts
# forge install OpenZeppelin/openzeppelin-contracts
# forge install foundry-rs/forge-std
